plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'com.llucs.nexusai'
    compileSdk 34

    defaultConfig {
        applicationId 'com.llucs.nexusai'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildFeatures {
        compose true
    }

    composeOptions {
        kotlinCompilerExtensionVersion '1.5.14'
    }

    kotlin {
        jvmToolchain(17)
    }

    kotlinOptions {
        allWarningsAsErrors = false

        jvmTarget = '17'
    }
}

dependencies {
    // Compose BOM 
    implementation platform('androidx.compose:compose-bom:2024.06.00')

    // Compose
    implementation 'androidx.activity:activity-compose:1.9.2'
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-extended'
    debugImplementation 'androidx.compose.ui:ui-tooling'

    // Necessário pro Theme.AppCompat.DayNight.NoActionBar
    implementation 'androidx.appcompat:appcompat:1.7.0'

    // Coroutines
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1'

    // Lifecycle
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.4'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.8.4'

    implementation "androidx.core:core-splashscreen:1.0.1"

    // Network
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

    // Data / JSON
    implementation 'androidx.datastore:datastore-preferences:1.1.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3'
}
dependencyLocking {
    lockAllConfigurations()
}
